// <auto-generated />
namespace Integrador.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fixdispositivoentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixdispositivoentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201901152129003_fix dispositivo entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
